name: All Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install sharutils
      run: sudo apt-get install sharutils
      
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - uses: actions/checkout@v4

    - name: Unit Tests
      run: cd src && python3 -m unittest discover -s test/unit

    - name: Integration Tests
      run: cd src && python3 -m unittest discover -s test/integration

    - name: System Quick Tests
      run: cd src && python3 -m unittest discover -s test/system/quick

    - name: System Slow Tests
      run: cd src && python3 -m unittest discover -s test/system/slow
