name: Build

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      sha:
        required: false
        type: string
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install sharutils
      run: sudo apt-get install sharutils

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.sha || github.ref }}

    - name: Unit Tests
      run: cd src && python3 -m unittest discover -s test/unit

    - name: Integration Tests
      run: cd src && python3 -m unittest discover -s test/integration

    - name: System Tests
      run: cd src && python3 -m unittest discover -s test/system

    - name: Build
      run: ./src/build.sh > dont_download2.sh

    - name: Release
      id: release
      run: |
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"
        ./.github/release.sh
