name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:  # 👈 Add job outputs
      new_build: ${{ steps.release_build.outputs.new_build }}

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.sha || github.ref }}

    - name: Unit Tests
      run: cd src && python3 -m unittest discover -s test/unit

    - name: Integration Tests
      run: cd src && python3 -m unittest discover -s test/integration

    - name: System Tests
      run: cd src && python3 -m unittest discover -s test/system

    - name: Build
      run: |
        set -euo pipefail
        SKIP_COMMIT=true ./src/build.sh | sha256sum > latest.id
        ./src/build.sh > dont_download2.sh

    - name: Release Build
      id: release_build
      run: |
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"
        python3 ./.github/release_build.py
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print new build
      if : steps.release_build.outputs.new_build == 'yes'
      run: echo "New build!"

  trigger_db_update:
    needs: build
    if: ${{ needs.build.outputs.new_build == 'yes' }}
    uses: ./.github/workflows/update_db.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
